version: '2.3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      MYSQL_DATABASE: social_network
      MYSQL_USER: social_network
      MYSQL_PASSWORD: social_network
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 15
  mysql_social_network_flyway:
    image: holuhoev/otus-hl-db-migration:${DOCKER_TAG}
    command: -url=jdbc:mysql://mysql:3306/social_network -user=social_network -password=social_network -connectRetries=15 migrate
    depends_on:
      mysql:
        condition: service_healthy
  backend:
    image: holuhoev/otus-hl-backend:${DOCKER_TAG}
    environment:
      - "--spring.profiles.active=demo"
      - "-Dlogging.level=TRACE"
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy


volumes:
  mysql_data:
    driver: local